// INFO: Parametes section.
:pki_url_nice_label: https://en.wikipedia.org/wiki/Public_key_infrastructure[Public Key Infrastructure (PKI)]
:hunspell_url_nice_label: https://en.wikipedia.org/wiki/Hunspell[Hunspell]

= Public Key Infrastructure

This repository contains complex {pki_url_nice_label} solution with detailed description and the reference implementation. All questions related to the content please send to tomasz.orlowski@creotech.pl.

== TODO

Items planned to be added or extended:

.todo:
* Integrate spell checking like {hunspell_url_nice_label}.
* Integrate conditional PDF generation depending on profiles (ie. custommer, architect, developer, all, etc...).
* Implement redundant parameter detection.

== VS Code developer manual

List of VS Code extentions:
* AsciiDoc
* PlantUML Viewer

=== AsciiDoc

If you want to see generated `*.adoc` preview open file you are interrested in and press `ctrl+shift+v` key combination. New window should appear containing your generated `*.adoc` preview.

=== PlantUML Viewer

If you want to see generated `*.puml` preview open file you are interrested in and press `alt+d` key combination. Preview window should appear next to your `*.puml` code.
