// INFO: Parametes section.
:pki_url_nice_label: https://en.wikipedia.org/wiki/Public_key_infrastructure[Public-key infrastructure (PKI)]

:pub_key_cert_nice_label: https://en.wikipedia.org/wiki/Public_key_certificate[Public key certificate]

:pub_key_crypto: https://en.wikipedia.org/wiki/Public-key_cryptography[Public-key cryptography]

:hunspell_url_nice_label: https://en.wikipedia.org/wiki/Hunspell[Hunspell]

:some_source_file_adoc: some_source_file.adoc
:some_source_file_puml: some_source_file.puml

= Public-key infrastructure

This repository contains complex {pki_url_nice_label} solution with detailed description and the reference implementation. All questions related to the content please send to tomasz.orlowski@creotech.pl.

== General overview.

A {pki_url_nice_label} is a set of roles, policies, hardware, software and procedures needed to create, manage, distribute, use, store and revoke {pub_key_cert_nice_label}s and manage {pub_key_crypto}.

[plantuml, format="png", id="myDiagram"]
----
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
@enduml
----

== VS Code developer manual

List of VS Code extentions:

* AsciiDoc
* PlantUML Viewer

=== AsciiDoc

If you want to see generated `{some_source_file_adoc}` preview open file you are interrested in and press `ctrl+shift+v` key combination. New window should appear containing your generated `{some_source_file_adoc}` preview.

=== PlantUML Viewer

If you want to see generated `{some_source_file_puml}` preview open file you are interrested in and press `alt+d` key combination. Preview window should appear next to your `{some_source_file_puml}` code.

== TODO

Items planned to be added or extended:

.todo:
* Integrate spell checking like {hunspell_url_nice_label}.
* Integrate conditional PDF generation depending on profiles (ie. custommer, architect, developer, all, etc...).
* Implement redundant parameter detection.
* PDF generator.
* Redundant and unused parameters detector.
* Unknown parameters detector.
