// INFO: Parametes section (URLs).
:pki_url_nice_label: https://en.wikipedia.org/wiki/Public_key_infrastructure[Public-key infrastructure (PKI)]

:pub_key_cert_nice_label: https://en.wikipedia.org/wiki/Public_key_certificate[Public-key certificate]

:hunspell_url_nice_label: https://en.wikipedia.org/wiki/Hunspell[Hunspell]

:pub_key_crypto_url_nice_label: https://en.wikipedia.org/wiki/Public-key_cryptography[Public-key cryptography]

:vscode_url_nice_label: https://en.wikipedia.org/wiki/Visual_Studio_Code[Visual Studio Code]

:asciidoctor_plantuml_url_nice_label: https://github.com/hsanson/asciidoctor-plantuml?tab=readme-ov-file#docker[PlantUML Server]

:docker_url_nice_label: https://en.wikipedia.org/wiki/Docker_(software)[Docker]

:computer_security_url_nice_label: https://en.wikipedia.org/wiki/Computer_security[Computer security]

:nsc_url_nice_label: https://www.gov.pl/web/baza-wiedzy/narodowe-standardy-cyber[Polish National Cybersecurity Standards]

:nsc_800_52_url_nice_label: https://www.gov.pl/attachment/e3804a73-2d3e-4232-bc6d-9bbb4ba697bb[Guidelines for the Selection, Configuration, and Use of Transport Layer Security (TLS) Implementations called NSC 800-52 published on December 2023]

:nist_url_nice_label: https://www.nist.gov[National Institute of Standards and Technology]

:nist_800_52_url_nice_label: https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-52r2.pdf[Guidelines for the Selection, Configuration, and Use of Transport Layer Security (TLS) Implementations called NIST Special Publication 800-52 Revision 2 published in August 2019]

:tls_url_nice_label: https://en.wikipedia.org/wiki/Transport_Layer_Security[Transport Layer Security (TLS)]

:crypt_protocol_url_nice_label: https://en.wikipedia.org/wiki/Cryptographic_protocol[Cryptographic protocol]

:comm_protocol_url_nice_label: https://en.wikipedia.org/wiki/Communication_protocol[Communication protocol]

:cryptography_url_nice_label: https://en.wikipedia.org/wiki/Cryptography[Cryptography]

:present_layer_url_nice_label: https://en.wikipedia.org/wiki/Presentation_layer[Presentation layer]

:handshake_url_nice_label: https://en.wikipedia.org/wiki/Handshake_(computing)[Handshake]

// INFO: Parametes section (labels).

:local_user: user
:local_hostname: localhost

:some_source_file_adoc: some_source_file.adoc
:some_source_file_puml: some_source_file.puml

:plantuml_server_name: plantumlserver

= Public-key infrastructure

This repository contains complex {pki_url_nice_label} solution with detailed description and the reference implementation. All questions related to the content please send to tomasz.orlowski@creotech.pl.

== General overview and scope of this document

A {pki_url_nice_label} is a set of roles, policies, hardware, software and procedures needed to create, manage, distribute, use, store and revoke {pub_key_cert_nice_label}s and using {pub_key_crypto_url_nice_label}.

IMPORTANT: This document covers only small subset of extensive {computer_security_url_nice_label} subject and focuses only on technical aspects of the implementation. It is mainly based of {nsc_url_nice_label}, particulary {nsc_800_52_url_nice_label} reated to {nist_url_nice_label}, particulary {nist_800_52_url_nice_label}.

This document covers mailny {tls_url_nice_label} in version 1.3.

{tls_url_nice_label} is a {crypt_protocol_url_nice_label} designed to provide communications {computer_security_url_nice_label} over a computer network, such as the Internet. The {comm_protocol_url_nice_label} is widely used in applications such as email, instant messaging, and voice over IP, but its use in securing HTTPS remains the most publicly visible.

The {tls_url_nice_label} protocol aims primarily to provide security, including privacy (confidentiality), integrity, and authenticity through the use of {cryptography_url_nice_label}, such as the use of {pub_key_cert_nice_label}, between two or more communicating computer applications. It runs in the {present_layer_url_nice_label} and is itself composed of two layers: the {tls_url_nice_label} record and the {tls_url_nice_label} {handshake_url_nice_label} {comm_protocol_url_nice_label}.

== General solution architecture description

{tls_url_nice_label} based on {pki_url_nice_label} consist of three main groups:

* <<Certificate Authority>>
* <<TLS Server>>
* <<TLS Client>>

=== Certificate Authority


=== TLS Server


=== TLS Client

[plantuml, format="png", id="relation_to_ca"]
----
@startuml

left to right direction

rectangle Client
rectangle Server

Client --> Server

@enduml
----

Diagram below shows simplified architecture for complex {pki_url_nice_label} solution described in this document. 

[plantuml, format="png", id="relation_to_ca"]
----
@startuml

'left to right direction
top to bottom direction

rectangle CA
rectangle Server
rectangle Client

CA --> Server
CA --> Client

@enduml
----

// INFO: Page separator
[%always]
<<<

== VS Code developer manual

List of useful {vscode_url_nice_label} extentions used for development:

* AsciiDoc
* PlantUML Viewer
* Docker

=== AsciiDoc

If you want to see generated `{some_source_file_adoc}` preview open file you are interrested in and press `ctrl+shift+v` key combination. New window should appear containing your generated `{some_source_file_adoc}` preview.

=== PlantUML Viewer

If you want to see generated `{some_source_file_puml}` preview open file you are interrested in and press `alt+d` key combination. Preview window should appear next to your `{some_source_file_puml}` code.

=== Docker

Docker extension is used only to see currently running images. It is not mandatory. It is possible to check status of running PlantUML server docker image via CLI. Check section dedicated to <<PlantUML Server>> for details.

== PlantUML Server

According to the README article {asciidoctor_plantuml_url_nice_label} PlantUML Server can be launched locally in {docker_url_nice_label} via command line.

[subs="+attributes"]
-------------------------------------------------------------------------------
docker run -d --name {plantuml_server_name} -p 8081:8080 plantuml/plantuml-server:jetty
-------------------------------------------------------------------------------

You can verify if PlantUML Server {docker_url_nice_label} container is already running from command line.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ docker ps --format '{{.Names}}' | grep {plantuml_server_name}
{plantuml_server_name}
-------------------------------------------------------------------------------

// INFO: Page separator
[%always]
<<<

== TODO

Items planned to be added or extended:

.todo:
* Integrate spell checking like {hunspell_url_nice_label}.
* Integrate conditional PDF generation depending on profiles (ie. custommer, architect, developer, all, etc...).
* Implement redundant/unused parameters detection.
* Implement unknown parameters detector and rise build error for that.
* Implement proper PDF generator for PlantUML diagrams. Source of information: https://fiveandahalfstars.ninja/blog/2017/2017-05-01-plantuml-and-pdf
